permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: wangzhili
  email: wangstdio.h@gmail.com
  github: http://github.com/uglyname

# 站点信息
title: 王志立的博客
description: My personal blog
url: http://www.wangzhili.net
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /source/my.png
favicon: /source/my.png

# pygments: true
highlighter: pygments
# google analytics 设置
#ga:
#  id: UA-54262064-1 
# url: www.wangzhili.net

# disqus 设置
disqus:
  shortname: wangzhili

# 主题设置，自动激活某个标签
#active: 读书

# 首页除了最新文章外显示分类
#cates: 
# - 矩阵补全
# - LaTeX

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档


paginate: 5
paginate_path: "page:num"
