markdown: rdiscount
pygments: true
permalink: /:year/:month/:day/:title.html
name: "wangzhili"
markdown: rdiscount

author: "wanghzili"
atom-baseurl: "http://uglyname.github.io/"
disqus: "gopherwood"


